baseurl = "https://eloquent-nightingale-aac487.netlify.com/"
languageCode = "en-us"
title = "Clueless Coder"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
#disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"


[params]
    site_author = "Clueless"
    site_description = "The awesome blog of the Clueless Coder."
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/male_blue.gif"
    header_background = "img/boy-using-computer.jpg"
    header_title = "Clueless Coder"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Define which content types are shown on the homepage
    mainSections = ["post"]

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "Guero-Webb"
    gplus     = ""
